export const ME = {
  id: 'me',
  name: 'You',
  username: '@you',
  initials: 'YO',
  handicap: 12.4,
  homeCourse: 'Pebble Beach',
  avgScore: 84,
  bestScore: 76,
  roundsPlayed: 47,
  fairwayPct: 58,
  girPct: 44,
  avgPutts: 32,
};

export const FRIENDS = [
  { id: 1, name: 'Tyler Brooks', username: '@tyler_b', initials: 'TB', handicap: 8.2, avgScore: 80, bestScore: 71, roundsPlayed: 63, color: '#2d6a4f' },
  { id: 2, name: 'Jake Martinez', username: '@jakegolf', initials: 'JM', handicap: 14.1, avgScore: 86, bestScore: 78, roundsPlayed: 34, color: '#7c3aed' },
  { id: 3, name: 'Sam Lee', username: '@samlee', initials: 'SL', handicap: 6.0, avgScore: 77, bestScore: 68, roundsPlayed: 89, color: '#0369a1' },
  { id: 4, name: 'Chris Park', username: '@chrispark', initials: 'CP', handicap: 18.5, avgScore: 91, bestScore: 83, roundsPlayed: 21, color: '#b45309' },
  { id: 5, name: 'Alex Rivera', username: '@arivera', initials: 'AR', handicap: 10.3, avgScore: 82, bestScore: 74, roundsPlayed: 55, color: '#be185d' },
];

export const FEED_POSTS = [
  {
    id: 1,
    userId: 1,
    type: 'round',
    course: 'Augusta National',
    score: 74,
    par: 72,
    vsPar: '+2',
    stats: { fairways: '71%', gir: '61%', putts: 30 },
    caption: 'Best round of the year 🔥 Finally cracked 75!',
    time: '2h ago',
    likes: 24,
    comments: 7,
    reactions: { '🔥': 12, '😂': 2, '👏': 8, '😤': 3 },
    liked: false,
    challenged: false,
  },
  {
    id: 2,
    userId: 3,
    type: 'round',
    course: 'Torrey Pines',
    score: 71,
    par: 72,
    vsPar: '-1',
    stats: { fairways: '79%', gir: '72%', putts: 28 },
    caption: 'Under par baby. Who wants some?',
    time: '5h ago',
    likes: 41,
    comments: 15,
    reactions: { '🔥': 22, '😤': 9, '👏': 14, '😂': 5 },
    liked: true,
    challenged: false,
  },
  {
    id: 3,
    userId: 2,
    type: 'photo',
    caption: 'Finally fixed my driver slice 💪 Working with the new shaft flex',
    image: '🏌️',
    time: '1d ago',
    likes: 18,
    comments: 6,
    reactions: { '🔥': 8, '👏': 11, '😂': 1 },
    liked: false,
    challenged: false,
  },
  {
    id: 4,
    userId: 5,
    type: 'round',
    course: 'Pebble Beach',
    score: 82,
    par: 72,
    vsPar: '+10',
    stats: { fairways: '43%', gir: '33%', putts: 35 },
    caption: 'Rough day on the greens... but what a view 🌊',
    time: '2d ago',
    likes: 9,
    comments: 3,
    reactions: { '😂': 6, '👏': 4 },
    liked: false,
    challenged: false,
  },
];

export const LEADERBOARD_DATA = {
  friends: [
    { id: 3, name: 'Sam Lee', username: '@samlee', initials: 'SL', score: 77, rounds: 4, color: '#0369a1' },
    { id: 1, name: 'Tyler Brooks', username: '@tyler_b', initials: 'TB', score: 80, rounds: 3, color: '#2d6a4f' },
    { id: 5, name: 'Alex Rivera', username: '@arivera', initials: 'AR', score: 82, rounds: 5, color: '#be185d' },
    { id: 'me', name: 'You', username: '@you', initials: 'YO', score: 84, rounds: 3, color: '#64748b', isMe: true },
    { id: 2, name: 'Jake Martinez', username: '@jakegolf', initials: 'JM', score: 86, rounds: 2, color: '#7c3aed' },
    { id: 4, name: 'Chris Park', username: '@chrispark', initials: 'CP', score: 91, rounds: 1, color: '#b45309' },
  ],
  school: [
    { id: 10, name: 'Mark Wilson', username: '@markw', initials: 'MW', score: 72, rounds: 6, color: '#2d6a4f' },
    { id: 11, name: 'Danny Cho', username: '@dannyc', initials: 'DC', score: 74, rounds: 5, color: '#7c3aed' },
    { id: 3, name: 'Sam Lee', username: '@samlee', initials: 'SL', score: 77, rounds: 4, color: '#0369a1' },
    { id: 1, name: 'Tyler Brooks', username: '@tyler_b', initials: 'TB', score: 80, rounds: 3, color: '#2d6a4f' },
    { id: 'me', name: 'You', username: '@you', initials: 'YO', score: 84, rounds: 3, color: '#64748b', isMe: true },
  ],
};

export const CHALLENGES = [
  {
    id: 1,
    type: 'active',
    title: 'Lowest score this weekend',
    stakes: 'Loser buys dinner 🍕',
    opponent: FRIENDS[0],
    myScore: null,
    theirScore: 78,
    deadline: '2 days',
    metric: 'Best single round score',
  },
  {
    id: 2,
    type: 'active',
    title: 'Most rounds this month',
    stakes: '$20 bet 💵',
    opponent: FRIENDS[1],
    myScore: 3,
    theirScore: 2,
    deadline: '9 days',
    metric: 'Rounds played in March',
    leading: true,
  },
  {
    id: 3,
    type: 'pending',
    title: 'Lowest handicap by end of year',
    stakes: 'Bragging rights 🏆',
    opponent: FRIENDS[4],
    myScore: 12.4,
    theirScore: 10.3,
    deadline: '274 days',
    metric: 'Handicap index',
  },
];

export const GROUPS = [
  {
    id: 1,
    name: 'State University Golf',
    type: 'College Team',
    icon: '🎓',
    color: '#1e40af',
    members: 14,
    bg: '#dbeafe',
    description: 'Official team leaderboard & events',
  },
  {
    id: 2,
    name: 'Weekend Warriors',
    type: 'Friend Group',
    icon: '⛳',
    color: '#2d6a4f',
    members: 6,
    bg: '#d8f3dc',
    description: 'Weekly rounds and trash talk',
  },
  {
    id: 3,
    name: 'Pebble Beach Members',
    type: 'Golf Club',
    icon: '🏌️',
    color: '#92400e',
    members: 48,
    bg: '#fef3c7',
    description: 'Club leaderboard and events',
  },
];

export const MESSAGES = [
  { id: 1, with: FRIENDS[0], lastMsg: 'You down for 18 on Saturday?', time: '10m', unread: true },
  { id: 2, with: FRIENDS[1], lastMsg: 'Haha no chance you beat me 😂', time: '2h', unread: true },
  { id: 3, with: FRIENDS[2], lastMsg: 'Great round today man', time: '1d', unread: false },
  { id: 4, name: 'Weekend Warriors', isGroup: true, lastMsg: 'Tyler: I got tee time at 8am', time: '3h', unread: true, icon: '⛳' },
];

export const COURSES = [
  'Pebble Beach Golf Links',
  'Augusta National',
  'Torrey Pines GC (South)',
  'Bethpage Black',
  'Oakmont Country Club',
  'Shinnecock Hills',
  'Merion Golf Club',
  'TPC Sawgrass',
  'Pinehurst No. 2',
  'Riviera Country Club',
];

export const HOLE_DATA = [
  { hole: 1, par: 4, yards: 412 },
  { hole: 2, par: 5, yards: 545 },
  { hole: 3, par: 3, yards: 175 },
  { hole: 4, par: 4, yards: 438 },
  { hole: 5, par: 4, yards: 411 },
  { hole: 6, par: 3, yards: 196 },
  { hole: 7, par: 4, yards: 392 },
  { hole: 8, par: 5, yards: 521 },
  { hole: 9, par: 4, yards: 460 },
  { hole: 10, par: 4, yards: 404 },
  { hole: 11, par: 3, yards: 188 },
  { hole: 12, par: 4, yards: 425 },
  { hole: 13, par: 5, yards: 510 },
  { hole: 14, par: 4, yards: 445 },
  { hole: 15, par: 3, yards: 163 },
  { hole: 16, par: 4, yards: 398 },
  { hole: 17, par: 4, yards: 441 },
  { hole: 18, par: 5, yards: 548 },
];
